#ifndef __PIN_FUNCTION_DEFINES_H__
#define __PIN_FUNCTION_DEFINES_H__

#define PIN_FUNCTION1 0
#define PIN_FUNCTION2 1
#define PIN_FUNCTION3 2
#define PIN_FUNCTION4 3

#define AIN0_0_27 PIN_FUNCTION2
#define AIN0_0_28 PIN_FUNCTION2
#define AIN0_0_29 PIN_FUNCTION2
#define AIN0_0_30 PIN_FUNCTION2

#endif
